use rusqlite::{Connection, params};
use crate::{ apy_fetcher};
use chrono::prelude::*;

pub fn create_rates_databases(){
    create_mango_rates_database();
}

pub async fn update_rates_databases(){
    mango_insert_data().await;
}

pub fn create_mango_rates_database(){
    let conn = Connection::open("rates.db").unwrap();
    conn.execute("create table if not exists rates(
        protocol text ,
        time text,
        usdc_deposit_rate real,
        usdc_borrow_rate real,
        usdc_utilization_rate real,
        mngo_deposit_rate real,
        mngo_borrow_rate real,
        mngo_utilization_rate real,
        btc_deposit_rate real,
        btc_borrow_rate real,
        btc_utilization_rate real,
        eth_deposit_rate real,
        eth_borrow_rate real,
        eth_utilization_rate real,
        sol_deposit_rate real,
        sol_borrow_rate real,
        sol_utilization_rate real,
        usdt_deposit_rate real,
        usdt_borrow_rate real,
        usdt_utilization_rate real,
        srm_deposit_rate real,
        srm_borrow_rate real,
        srm_utilization_rate real,
        ray_deposit_rate real,
        ray_borrow_rate real,
        ray_utilization_rate real,
        cope_deposit_rate real,
        cope_borrow_rate real,
        cope_utilization_rate real,
        ftt_deposit_rate real,
        ftt_borrow_rate real,
        ftt_utilization_rate real,
        msol_deposit_rate real,
        msol_borrow_rate real,
        msol_utilization_rate real,
        bnb_deposit_rate real,
        bnb_borrow_rate real,
        bnb_utilization_rate real,
        avax_deposit_rate real,
        avax_borrow_rate real,
        avax_utilization_rate real,
        luna_deposit_rate real,
        luna_borrow_rate real,
        luna_utilization_rate real
        )", []).unwrap();
}

pub async fn mango_insert_data() {
    let data = apy_fetcher::get_current_mango_apys().await.unwrap();
    let conn = Connection::open("rates.db").unwrap();
    conn.execute("INSERT INTO rates (
        protocol,
        time,
        usdc_deposit_rate,
        usdc_borrow_rate,
        usdc_utilization_rate,
        mngo_deposit_rate,
        mngo_borrow_rate,
        mngo_utilization_rate,
        btc_deposit_rate,
        btc_borrow_rate,
        btc_utilization_rate,
        eth_deposit_rate,
        eth_borrow_rate,
        eth_utilization_rate,
        sol_deposit_rate,
        sol_borrow_rate,
        sol_utilization_rate,
        usdt_deposit_rate,
        usdt_borrow_rate,
        usdt_utilization_rate,
        srm_deposit_rate,
        srm_borrow_rate,
        srm_utilization_rate,
        ray_deposit_rate,
        ray_borrow_rate,
        ray_utilization_rate,
        cope_deposit_rate,
        cope_borrow_rate,
        cope_utilization_rate,
        ftt_deposit_rate,
        ftt_borrow_rate,
        ftt_utilization_rate,
        msol_deposit_rate,
        msol_borrow_rate,
        msol_utilization_rate,
        bnb_deposit_rate,
        bnb_borrow_rate,
        bnb_utilization_rate,
        avax_deposit_rate,
        avax_borrow_rate,
        avax_utilization_rate,
        luna_deposit_rate,
        luna_borrow_rate,
        luna_utilization_rate
        ) values (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25, ?26, ?27, ?28, ?28, ?30, ?31, ?32, ?33, ?34, ?35, ?36, ?37, ?38, ?39, ?40, ?41, ?42, ?43, ?44)", params![
        data.protocol,
        Utc::now().to_string(),
        data.usdc.deposit_rate,
        data.usdc.borrow_rate,
        data.usdc.utilization_rate,
        data.mngo.deposit_rate,
        data.mngo.borrow_rate,
        data.mngo.utilization_rate,
        data.btc.deposit_rate,
        data.btc.borrow_rate,
        data.btc.utilization_rate,
        data.eth.deposit_rate,
        data.eth.borrow_rate,
        data.eth.utilization_rate,
        data.sol.deposit_rate,
        data.sol.borrow_rate,
        data.sol.utilization_rate,
        data.usdt.deposit_rate,
        data.usdt.borrow_rate,
        data.usdt.utilization_rate,
        data.srm.deposit_rate,
        data.srm.borrow_rate,
        data.srm.utilization_rate,
        data.ray.deposit_rate,
        data.ray.borrow_rate,
        data.ray.utilization_rate,
        data.cope.deposit_rate,
        data.cope.borrow_rate,
        data.cope.utilization_rate,
        data.ftt.deposit_rate,
        data.ftt.borrow_rate,
        data.ftt.utilization_rate,
        data.msol.deposit_rate,
        data.msol.borrow_rate,
        data.msol.utilization_rate,
        data.bnb.deposit_rate,
        data.bnb.borrow_rate,
        data.bnb.utilization_rate,
        data.avax.deposit_rate,
        data.avax.borrow_rate,
        data.avax.utilization_rate,
        data.luna.deposit_rate,
        data.luna.borrow_rate,
        data.luna.utilization_rate]).unwrap();
}